### ISSUE TITLE
npm start error

### ISSUE THREAD

**Issue by Shahjalal7311** [nodebeats/nodebeats#1]
Node version :5.12.0
mongo version: 3.2
getting this error when start the server

> admin@0.0.0 start D:\node_cms\admin
> ng serve --proxy-config proxy.conf.json

Unexpected token {
SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:387:25)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (D:\node_cms\admin\node_modules\@ngtools\webpack\src\i
ndex.js:6:10)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (D:\node_cms\admin\node_modules\angular-cli\models\web
pack-build-typescript.js:5:17)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (D:\node_cms\admin\node_modules\angular-cli\models\web
pack-config.js:2:34)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (D:\node_cms\admin\node_modules\angular-cli\tasks\buil
d-webpack.js:6:24)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (D:\node_cms\admin\node_modules\angular-cli\commands\b
uild.js:3:23)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:20:19)
    at Class.module.exports.includedCommands (D:\node_cms\admin\node_modules\ang
ular-cli\addon\index.js:21:16)
    at D:\node_cms\admin\node_modules\angular-cli\lib\models\project.js:392:61
    at Array.forEach (native)
    at Project.addonCommands (D:\node_cms\admin\node_modules\angular-cli\lib\mod
els\project.js:391:15)
    at Project.eachAddonCommand (D:\node_cms\admin\node_modules\angular-cli\lib\
models\project.js:426:30)
    at module.exports (D:\node_cms\admin\node_modules\angular-cli\lib\cli\lookup
-command.js:33:13)
    at CLI.<anonymous> (D:\node_cms\admin\node_modules\angular-cli\lib\cli\cli.j
s:34:26)
    at tryCatch (D:\node_cms\admin\node_modules\rsvp\dist\rsvp.js:538:12)
    at invokeCallback (D:\node_cms\admin\node_modules\rsvp\dist\rsvp.js:553:13)
    at publish (D:\node_cms\admin\node_modules\rsvp\dist\rsvp.js:521:7)
    at flush (D:\node_cms\admin\node_modules\rsvp\dist\rsvp.js:2373:5)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v5.12.0
npm ERR! npm  v3.8.6
npm ERR! code ELIFECYCLE
npm ERR! admin@0.0.0 start: `ng serve --proxy-config proxy.conf.json`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the admin@0.0.0 start script 'ng serve --proxy-config proxy.c
onf.json'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the admin package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     ng serve --proxy-config proxy.conf.json
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs admin
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls admin
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\node_cms\admin\npm-debug.log

**Comment by ShrawanLakhe** [comment]
Hi,, have you installed angular-cli package globally in your system?

**Comment by Shahjalal7311** [comment]
yes, angular-cli package install globally in my system

**Comment by ShrawanLakhe** [comment]
if so, then i think another one to take care of is have you run npm install command inside admin directory?
You have to run npm install command inside admin directory as well
