### ISSUE TITLE
Module version error

### ISSUE THREAD

**Issue by ghost** [nodebeats/nodebeats#13]
Hi, 
I just cloned and installed nodebeats but there were errors while installing.
When I ran command "npm start" the following error is thrown.
nodebeats@0.0.2 start /var/www/html/nodebeats
> node server.js

module.js:597
  return process.dlopen(module, path._makeLong(filename));
                 ^

Error: Module version mismatch. Expected 48, got 57.
    at Error (native)
    at Object.Module._extensions..node (module.js:597:18)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/var/www/html/nodebeats/node_modules/bcrypt/bcrypt.js:6:16)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at /var/www/html/nodebeats/lib/auth/hasher.js:6:18
    at Object.<anonymous> (/var/www/html/nodebeats/lib/auth/hasher.js:63:3)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! nodebeats@0.0.2 start: `node server.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the nodebeats@0.0.2 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/prdxn93/.npm/_logs/2018-06-19T13_31_52_456Z-debug.log

**Comment by avsek477** [comment]
Try using "npm update"
