### ISSUE TITLE
error occured in font end when npm strat

### ISSUE THREAD

**Issue by Shahjalal7311** [nodebeats/nodebeats#2]
node version :5.12.
mongo version: 3.2
already install bcrypt module in globally and this package
module.js:341
    throw err;
    ^

Error: Cannot find module 'bcrypt'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:20:19)
    at D:\node_cms\lib\auth\hasher.js:10:18
    at Object.<anonymous> (D:\node_cms\lib\auth\hasher.js:67:3)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:20:19)
    at D:\node_cms\lib\helpers\environment.variable.generator.helper.js:10:18
    at Object.<anonymous> (D:\node_cms\lib\helpers\environment.variable.generato
r.helper.js:36:3)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:20:19)
    at D:\node_cms\lib\helpers\database.helper.js:15:46
    at Object.<anonymous> (D:\node_cms\lib\helpers\database.helper.js:120:3)

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v5.12.0
npm ERR! npm  v3.8.6
npm ERR! code ELIFECYCLE
npm ERR! nodebeats@0.0.2 start: `node server.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the nodebeats@0.0.2 start script 'node server.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the nodebeats package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node server.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs nodebeats
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls nodebeats
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\node_cms\npm-debug.log

**Comment by ShrawanLakhe** [comment]
It seems npm install did not run successfully. can you please check into that?

**Comment by Shahjalal7311** [comment]
everything i check ,but npm not install this system

node version:6.9.5
npm version 3.10.10

**Comment by ShrawanLakhe** [comment]
what is the error reported in the console while running npm install command?
