### ISSUE TITLE
Admin login page blank

### ISSUE THREAD

**Issue by thanateros** [nodebeats/nodebeats#8]
Just installed the docker images today as per [https://github.com/nodebeats/nodebeats](https://github.com/nodebeats/nodebeats) on Ubuntu 17.04 running in a VM (Hyper-V) on Windows 10.

The install and spin-up of the containers went without a hitch.  I could browser the site and everything looked great.

However, when I tried to access the admin interface at http://localhost:4200/login I get a blank page.

Docker log shows the following error:
```
nodebeats-node-dev-admin    |  50% building modules 351/521 modules 170 active ...dmin/node_modules/rxjs/operator/do.jswebpack: wait until bundle finished: /login
 86% hashingcrypto.js:74                                                                 
nodebeats-node-dev-admin    |   this._handle.update(data, encoding);
nodebeats-node-dev-admin    |                ^
nodebeats-node-dev-admin    |
nodebeats-node-dev-admin    | TypeError: Data must be a string or a buffer
nodebeats-node-dev-admin    |     at TypeError (native)
nodebeats-node-dev-admin    |     at Hash.update (crypto.js:74:16)
nodebeats-node-dev-admin    |     at HarmonyExportImportedSpecifierDependency.updateHash (/var/www/nodebeats/admin/node_modules/webpack/lib/dependencies/HarmonyExportImportedSpecifierDependency.js:144:8)
nodebeats-node-dev-admin    |     at /var/www/nodebeats/admin/node_modules/webpack/lib/DependenciesBlock.js:33:5
nodebeats-node-dev-admin    |     at Array.forEach (native)
nodebeats-node-dev-admin    |     at NormalModule.DependenciesBlock.updateHash (/var/www/nodebeats/admin/node_modules/webpack/lib/DependenciesBlock.js:32:20)
nodebeats-node-dev-admin    |     at NormalModule.Module.updateHash (/var/www/nodebeats/admin/node_modules/webpack/lib/Module.js:162:41)
nodebeats-node-dev-admin    |     at NormalModule.updateHash (/var/www/nodebeats/admin/node_modules/webpack/lib/NormalModule.js:327:30)
nodebeats-node-dev-admin    |     at modules.forEach.m (/var/www/nodebeats/admin/node_modules/webpack/lib/Chunk.js:253:31)
nodebeats-node-dev-admin    |     at Array.forEach (native)
nodebeats-node-dev-admin    |     at Chunk.updateHash (/var/www/nodebeats/admin/node_modules/webpack/lib/Chunk.js:253:16)
nodebeats-node-dev-admin    |     at Compilation.createHash (/var/www/nodebeats/admin/node_modules/webpack/lib/Compilation.js:1121:10)
nodebeats-node-dev-admin    |     at sealPart2 (/var/www/nodebeats/admin/node_modules/webpack/lib/Compilation.js:605:9)
nodebeats-node-dev-admin    |     at next (/var/www/nodebeats/admin/node_modules/tapable/lib/Tapable.js:184:11)
nodebeats-node-dev-admin    |     at Compilation.<anonymous> (/var/www/nodebeats/admin/node_modules/webpack/lib/ProgressPlugin.js:110:5)
nodebeats-node-dev-admin    |     at next (/var/www/nodebeats/admin/node_modules/tapable/lib/Tapable.js:186:14)
nodebeats-node-dev-admin    |
nodebeats-node-dev-admin    | npm info lifecycle admin2@0.0.0~start: Failed to exec start script
nodebeats-node-dev-admin    | npm ERR! Linux 4.10.0-28-generic
nodebeats-node-dev-admin    | npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
nodebeats-node-dev-admin    | npm ERR! node v6.9.1
nodebeats-node-dev-admin    | npm ERR! npm  v3.10.8
nodebeats-node-dev-admin    | npm ERR! code ELIFECYCLE
nodebeats-node-dev-admin    | npm ERR! admin2@0.0.0 start: `ng serve --proxy-config proxy.conf.json --host 0.0.0.0 --port 4200 --live-reload-port 49153`
nodebeats-node-dev-admin    | npm ERR! Exit status 1
nodebeats-node-dev-admin    | npm ERR!
nodebeats-node-dev-admin    | npm ERR! Failed at the admin2@0.0.0 start script 'ng serve --proxy-config proxy.conf.json --host 0.0.0.0 --port 4200 --live-reload-port 49153'.
nodebeats-node-dev-admin    | npm ERR! Make sure you have the latest version of node.js and npm installed.
nodebeats-node-dev-admin    | npm ERR! If you do, this is most likely a problem with the admin2 package,
nodebeats-node-dev-admin    | npm ERR! not with npm itself.
nodebeats-node-dev-admin    | npm ERR! Tell the author that this fails on your system:
nodebeats-node-dev-admin    | npm ERR!     ng serve --proxy-config proxy.conf.json --host 0.0.0.0 --port 4200 --live-reload-port 49153
```
I've started from scratch (git clone) several times following the instructions from the git page for this project and get this error every single time I try to log into the admin interface.

My company currently runs a Hippo CMS installation (Java-based) and none of the other devs knows Java; after some research I settled upon Nodebeats to replace it since the other devs do know js, css3, html5 and it looks like an enterprise-ready product.

Any help is appreciated, really want to try this out :)

**Comment by ShrawanLakhe** [comment]
Hi @thanateros  We are really sorry for the late reply. as for now, the project status is on halt. Due to some issues on the angualr cli, it is having some issues. We will be coming with the new release soon. Thank you!  
Once again really sorry for the late reply.

**Comment by thanateros** [comment]
I understand; I'll come back to this.  Thank you for the reply.

**Comment by ShrawanLakhe** [comment]
Thank you @thanateros
